### ISSUE TITLE
Add shows route 

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#109]
**Describe the feature**
Add shows eroute with JSON having `name` `genre` `rating` `description` `seasons` .

**Tasks Todo**
- [ ] Add  json file with appropiate data in `showsData.json`.
- [ ] Add endpoint `/shows` in `shows.ts`.
- [ ] Add enpoint `/shows/:id` in `shows.ts`.

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth I would like to work on it please assign it to me.

**Comment by ShauryaAg** [comment]
@Samridhi-98 **Anime** is a too specific topic. If you want you can add a **movies/shows** route.

**Comment by Samridhi-98** [comment]
> @Samridhi-98 **Anime** is a too specific topic. If you want you can add a **movies/shows** route.

Okay, I have updated it to shows route.
