### ISSUE TITLE
Adding Books route.

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#110]
**Describe the feature**
Add anime route with JSON having `title` `author` `rating` `description` `price`.

**Tasks Todo**
- [ ] Add  json file with appropiate data in `booksdata.json`.
- [ ] Add endpoint `/books` in `books.ts`.
- [ ] Add enpoint `/books/:id` in `books.ts`.

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg I would like to work on this issue. Plz, assign.
