### ISSUE TITLE
Add query params in shows route

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#116]
Add route to fetch based on genre, rating, seasons

**Tasks Todo**
 
- [ ] Add route with query param /shows?genre=abc
- [ ] Add route with query param /shows?rating=abc
- [ ]  Add route with query param /shows?seasons=abc

Are you working on this feature? (Yes)

**Comment by Samridhi-98** [comment]
@ShauryaAg @paramsiddharth  I would like to work on it please assign it to me.

**Comment by paramsiddharth** [comment]
@Samridhi-98 Please go ahead.
