### ISSUE TITLE
Add movies route

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#121]
**Describe the feature**
Add movies route with JSON having `title` `genre` `rating` `imgUrl` `description` .

**Tasks Todo**
- [ ] Add  json file with appropiate data in `moviesData.json`.
- [ ] Add endpoint `/movies` in `movies.ts`.
- [ ] Add enpoint `/movies/:id` in `movies.ts`.

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  I would like to work on it please assign it to me.
