### ISSUE TITLE
Add sports route

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#126]
**Describe the feature**
Add sports routes specialize in different types of sports like cricket, football, hockey, etc.
Like, currently add `sports/cricket` and `sports/cricket/2` with the following key-value pairs:
`playerName`, `age`, `nationality`, `imageUrl`, `description`,`jerseyNo`

**Tasks Todo**
- [ ] Add  json file with appropiate data in `data/sports/cricketData.json`
- [ ] Add endpoint `/sports/cricket` in `sports.ts`
- [ ] Add enpoint `/sports/cricket/:id` in `sports.ts`

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg @paramsiddharth I would like to work on it please assign it to me.
