### ISSUE TITLE
Extending user info 

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#127]
**Describe the feature**
Add following user details in the user schema

- [ ] nationality
- [ ] occupation
- [ ] age
- [ ] gender
- [ ] date of birth(DOB)

**Task TODO**
- [ ] update user schema with above-mentioned fields.
- [ ] update `user.ts` for the corresponding fields.
- [ ] update `usertest.ts` for the corresponding fields.

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg I would work on this issue plz assign.
