### ISSUE TITLE
Improve sports route with specialize

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#134]
**Describe the feature**
Improve sports routes specialization like, currently add `sports/football` and `sports/football/2` with the following key-value pairs: `playerName`, `age`, `nationality`, `imageUrl`, `description`,`jerseyNo`

**Tasks Todo**
- [ ] Add  json file with appropiate data in `data/sports/footballData.json`
- [ ] Add endpoint `/sports/football` in `sports.ts`
- [ ] Add enpoint `/sports/football/:id` in `sports.ts`

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  I would like to work on it please assign.

**Comment by paramsiddharth** [comment]
@Samridhi-98 OK! You may start with the PR.
