### ISSUE TITLE
Extend sports route

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#137]
**Describe the feature**
Improve sports routes specialization like, currently add `sports/football` and `sports/football/2` with the following key-value pairs: `playerName`, `age`, `nationality`, `imageUrl`, `description`,`jerseyNo`

**Tasks Todo**
- [ ] Add  json file with appropiate data in `data/sports/hockeyData.json`  &  `data/sports/basketballData.json` 
- [ ] Add endpoint `/sports/:category` in `sports.ts`
- [ ] Add enpoint `/sports/:category?player=abc` in `sports.ts`

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@paramsiddharth  @ShauryaAg  I would like to work on it please assign it to me.
