### ISSUE TITLE
Improvise photo route

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#145]
**Describe the feature**
Improve photo routes specialization like, currently add `photos/nature` and `photos/human` with the following key-value 
`image` `description` `name` .

**Tasks Todo**
- [ ] Add  json file with appropiate data in `data/photos/naturedata.json`  &  `data/photos/humandata.json` 
- [ ] Add endpoint `photos/:nature` in `photos.ts`
- [ ] Add endpoint `photos/human` in `photos.ts`

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  I would like to work on it please assign it to me.

**Comment by adityabisoi** [comment]
As mentioned in the Discord channel, we have sufficient endpoints now, so only frontend contributions will be accepted.

**Comment by Samridhi-98** [comment]
> As mentioned in the Discord channel, we have sufficient endpoints now, so only frontend contributions will be accepted.
Okay.
