### ISSUE TITLE
Update home page endpoints info

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#90]
**Describe the feature**
Update endpoints information on the home page.

**Tasks todo**
- [ ] Add `/foodphoto` with their additional params and query.
- [ ]  Add `/animals` with their additional params and query.
- [ ]  Add `/vehicles` with their additional params and query. 

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  I would like to work on it, please assign it to me.

**Comment by ShauryaAg** [comment]
Go ahead @Samridhi-98.
