### ISSUE TITLE
Adding address route with json data

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#95]
**Describe the feature**
Add address route with JSON having `dummy street data` `pin code` `city` `state` `country`.

**Tasks Todo**
- [ ] Add  json file with appropiate data in `addressData.json`.
- [ ] Add endpoint `/address` in `address.ts`.
- [ ] Add enpoint `/address/:id` in `address.ts`.

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg @paramsiddharth I would like to work on this will you please assign it to me.

**Comment by ShauryaAg** [comment]
Sure! @Samridhi-98
